stages:
  data_ingestion:
    cmd: python3 src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.url
    outs:
    - data/raw
  data_preprocessing:
    cmd: python3 src/data_preprocessing/data_preprocess.py
    deps:
    - data/raw
    - src/data_preprocessing/data_preprocess.py
    params:
    - data_preprocessing.test_size
    outs:
    - data/processed/test
    - data/processed/train

  feature_engineering:
    cmd: python3 src/features/feature_engineering.py
    deps:
    - data/processed/train
    - src/features/feature_engineering.py
    outs:
    - vectorizer/vectorizer.pkl
  model_building:
    cmd: python3 src/models/model_building.py
    deps:
    - vectorizer/vectorizer.pkl
    - data/processed/test
    outs:
    - model/model.pkl

  model_evalution:
    cmd: python3 src/models/model_evaluation.py
    deps:
    - model
    - src/models/model_evaluation.py
    - vectorizer
    metrics:
    - Metric/metric.yaml:
        cache: false
