stages:
  data_ingestion:
    cmd: python3 src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
    params:
      - data_ingestion.url
    outs:
      - data/raw

  data_preprocessing:
    cmd: python3 src/data_preprocessing/data_preprocess.py
    deps:
      - src/data_preprocessing/data_preprocess.py
      - data/raw
    params:
      - data_preprocessing.test_size
    outs:
      - data/processed/train
      - data/processed/test

  feature_engineering:
    cmd: python3 src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/processed/train
    outs:
      - vectorizer/vectorizer.pkl

  model_building:
    cmd: python3 src/models/model_building.py
    deps:
      - src/models/model_building.py
      - vectorizer/vectorizer.pkl
      - data/processed/train
    outs:
      - model/model.pkl

  model_evaluation:
    cmd: python3 src/models/model_evaluation.py
    deps:
      - src/models/model_evaluation.py
      - model/model.pkl
      - vectorizer/vectorizer.pkl
      - data/processed/test
    outs:
      - model_info/experiment.json
    metrics:
      - Metric/metric.yaml:
          cache: false

  register_model:
    cmd: python3 src/models/model_register.py
    deps:
      - src/models/model_register.py
      - model_info/experiment.json

